# Generated by Django 6.0.5 on 2026-06-26 17:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='optimization_problems/rooms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='optimization_problems/solution/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('created', 'Created'), ('problem_family_selected', 'Problem family selected'), ('problem_subtype_selected', 'Problem subtype selected'), ('file_uploaded', 'File uploaded'), ('mapping_completed', 'Mapping completed'), ('objectives_selected', 'Objectives selected'), ('constraints_selected', 'Constraints selected'), ('review_ready', 'Review ready'), ('finalized', 'Finalized')], default='created', max_length=50)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('problem_family', models.CharField(blank=True, default='', max_length=100)),
                ('problem_subtype', models.CharField(blank=True, default='', max_length=100)),
                ('mapping_data', models.JSONField(blank=True, default=dict)),
                ('rooms_mapping_data', models.JSONField(blank=True, default=dict)),
                ('room_feature_resolution', models.JSONField(blank=True, default=dict)),
                ('selected_constraints', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_rooms_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_drafts', to='optimization_problems.roomdatafile')),
                ('uploaded_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_drafts', to='optimization_problems.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('algorithm_used', models.CharField(blank=True, default='', max_length=100)),
                ('used_parameters', models.JSONField(blank=True, default=dict)),
                ('partition_type', models.CharField(blank=True, default='', max_length=50)),
                ('reuse_solution', models.BooleanField(default=False)),
                ('constraint_values', models.JSONField(blank=True, default=dict)),
                ('penalty_summary', models.JSONField(blank=True, default=dict)),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('partition_count', models.IntegerField(default=0)),
                ('schedule_file', models.FileField(blank=True, null=True, upload_to='optimization_problems/solutions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='optimization_problems.problemdraft')),
            ],
        ),
    ]
