# Generated by Django 6.0.3 on 2026-04-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='mapping_data',
        ),
        migrations.CreateModel(
            name='ProblemDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('created', 'Created'), ('problem_family_selected', 'Problem family selected'), ('problem_subtype_selected', 'Problem subtype selected'), ('file_uploaded', 'File uploaded'), ('mapping_completed', 'Mapping completed'), ('objectives_selected', 'Objectives selected'), ('constraints_selected', 'Constraints selected'), ('review_ready', 'Review ready'), ('finalized', 'Finalized')], default='created', max_length=50)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('problem_family', models.CharField(blank=True, default='', max_length=100)),
                ('problem_subtype', models.CharField(blank=True, default='', max_length=100)),
                ('wizard_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_drafts', to='optimization_problems.schedule')),
            ],
        ),
    ]
