# Generated by Django 6.0.5 on 2026-06-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='execution_time_seconds',
            field=models.FloatField(default=0.0),
        ),
    ]
