# Generated by Django 6.0.3 on 2026-04-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0002_remove_schedule_mapping_data_problemdraft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemdraft',
            old_name='wizard_data',
            new_name='mapping_data',
        ),
        migrations.AddField(
            model_name='problemdraft',
            name='selected_constraints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problemdraft',
            name='selected_objectives',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
