# Generated by Django 6.0.3 on 2026-04-27 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0003_rename_wizard_data_problemdraft_mapping_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdraft',
            name='additional_data_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='problemdraft',
            name='additional_data_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='problemdraft',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('problem_family_selected', 'Problem family selected'), ('problem_subtype_selected', 'Problem subtype selected'), ('file_uploaded', 'File uploaded'), ('mapping_completed', 'Mapping completed'), ('objectives_selected', 'Objectives selected'), ('constraints_selected', 'Constraints selected'), ('additional_data_pending', 'Additional data pending'), ('additional_data_completed', 'Additional data completed'), ('review_ready', 'Review ready'), ('finalized', 'Finalized')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='file',
            field=models.FileField(upload_to='optimization_problems/schedules/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])]),
        ),
        migrations.CreateModel(
            name='ProblemExtraFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('caracteristicas_salas', 'Características das salas'), ('outro', 'Outro')], max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(upload_to='optimization_problems/extra_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_files', to='optimization_problems.problemdraft')),
            ],
        ),
    ]
