# Generated by Django 6.0.5 on 2026-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0003_remove_solution_execution_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
