# Generated by Django 6.0.5 on 2026-07-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0004_solution_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='baseline_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
