# Generated by Django 6.0.3 on 2026-04-28 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0004_problemdraft_additional_data_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAdditionalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(upload_to='optimization_problems/additional/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='problemdraft',
            name='additional_room_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_drafts', to='optimization_problems.problemadditionalfile'),
        ),
        migrations.DeleteModel(
            name='ProblemExtraFile',
        ),
    ]
