# Generated by Django 6.0.5 on 2026-07-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0005_solution_baseline_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='baseline_metrics',
        ),
        migrations.AddField(
            model_name='problemdraft',
            name='baseline_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
