# Generated by Django 6.0.3 on 2026-04-30 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0005_problemadditionalfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='optimization_problems/rooms.py/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='problemdraft',
            name='additional_room_file',
        ),
        migrations.RenameField(
            model_name='problemdraft',
            old_name='additional_data_config',
            new_name='rooms_mapping_data',
        ),
        migrations.RemoveField(
            model_name='problemdraft',
            name='additional_data_mapping',
        ),
        migrations.AlterField(
            model_name='problemdraft',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('problem_family_selected', 'Problem family selected'), ('problem_subtype_selected', 'Problem subtype selected'), ('file_uploaded', 'File uploaded'), ('mapping_completed', 'Mapping completed'), ('objectives_selected', 'Objectives selected'), ('constraints_selected', 'Constraints selected'), ('review_ready', 'Review ready'), ('finalized', 'Finalized')], default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='problemdraft',
            name='uploaded_rooms_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_drafts', to='optimization_problems.roomdatafile'),
        ),
        migrations.DeleteModel(
            name='ProblemAdditionalFile',
        ),
    ]
