# Generated by Django 6.0.3 on 2026-05-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0006_roomdatafile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemdraft',
            name='selected_objectives',
        ),
    ]
