# Generated by Django 6.0.5 on 2026-05-28 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0007_remove_problemdraft_selected_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdatafile',
            name='file',
            field=models.FileField(upload_to='optimization_problems/rooms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])]),
        ),
    ]
