# Generated by Django 6.0.5 on 2026-06-08 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0008_alter_roomdatafile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed')], default='created', max_length=20)),
                ('algorithm_used', models.CharField(blank=True, default='', max_length=100)),
                ('used_parameters', models.JSONField(blank=True, default=dict)),
                ('partition_type', models.CharField(blank=True, default='', max_length=50)),
                ('reuse_solution', models.BooleanField(default=False)),
                ('constraint_values', models.JSONField(blank=True, default=dict)),
                ('penalty_summary', models.JSONField(blank=True, default=dict)),
                ('schedule_file', models.FileField(blank=True, null=True, upload_to='solutions/schedules/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='optimization_problems.problemdraft')),
            ],
        ),
    ]
