# Generated by Django 6.0.5 on 2026-06-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0009_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='schedule_file',
            field=models.FileField(blank=True, null=True, upload_to='optimization_problems/solutions/'),
        ),
    ]
