# Generated by Django 6.0.5 on 2026-06-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_problems', '0010_alter_solution_schedule_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
