PROBLEM_SCHEMA = {
    "id": "university_course_timetabling",
    "label": "Horários universitários",
    "description": "Schema base para problemas de elaboração de horários universitários.",
    "fields": [
        {
            "key": "unidade_curricular",
            "label": "Unidade curricular",
            "description": "Nome ou identificador da unidade curricular.",
            "required": True,
            "data_type": "string",
            "aliases": ["unidade curricular", "uc", "cadeira", "disciplina", "course", "subject"],
        },
        {
            "key": "curso",
            "label": "Curso",
            "description": "Curso que está associado à aula.",
            "required": False,
            "data_type": "string",
            "aliases": ["curso", "degree"],
        },
        {
            "key": "turma",
            "label": "Turma",
            "description": "Turma ou grupo associado à aula.",
            "required": False,
            "data_type": "string",
            "aliases": ["turma", "class", "group", "class group"],
        },
        {
            "key": "turno",
            "label": "Turno da aula",
            "description": "Turno da aula.",
            "required": False,
            "data_type": "string",
            "aliases": ["turno, shift"],
        },
        {
            "key": "sala",
            "label": "Sala",
            "description": "Sala onde a aula decorre.",
            "required": True,
            "data_type": "string",
            "aliases": ["sala", "room"],
        },
        {
            "key": "caracteristicas_pedidas_para_sala",
            "label": "Características pedidas para sala",
            "description": "Características ou requisitos pedidos para a sala.",
            "required": False,
            "data_type": "string",
            "aliases": [
                "caracteristicas pedidas para sala",
                "características pedidas para sala",
                "requisitos sala",
                "room requirements",
                "requested room features",
            ],
        },
        {
            "key": "dia",
            "label": "Dia",
            "description": "Dia da aula.",
            "required": True,
            "data_type": "string",
            "aliases": ["dia", "day"],
        },
        {
            "key": "hora_inicio",
            "label": "Hora de início",
            "description": "Hora de início da aula.",
            "required": True,
            "data_type": "time",
            "aliases": ["hora inicio", "inicio", "start time", "begin", "start"],
        },
        {
            "key": "hora_fim",
            "label": "Hora de fim",
            "description": "Hora de fim da aula.",
            "required": True,
            "data_type": "time",
            "aliases": ["hora fim", "fim", "end time", "end"],
        },
        {
            "key": "numero_estudantes",
            "label": "Número de estudantes",
            "description": "Número de alunos inscritos ou esperados.",
            "required": False,
            "data_type": "number",
            "aliases": ["numero estudantes", "estudantes", "alunos", "inscritos", "students", "number of students"],
        },
    ],
}