PROBLEM_SCHEMA = {
    "id": "university_course_timetabling",
    "label": "Horários universitários",
    "description": "Schema base para problemas de elaboração de horários universitários.",
    "fields": [
        {
            "key": "unidade_curricular",
            "label": "Unidade curricular",
            "description": "Nome ou identificador da unidade curricular.",
            "required": True,
            "data_type": "string",
            "aliases": ["unidade curricular", "uc", "cadeira", "disciplina", "course", "subject"],
        },
        {
            "key": "docente",
            "label": "Docente",
            "description": "Docente responsável pela aula.",
            "required": False,
            "data_type": "string",
            "aliases": ["docente", "professor", "teacher"],
        },
        {
            "key": "turma",
            "label": "Turma",
            "description": "Turma ou grupo associado à aula.",
            "required": False,
            "data_type": "string",
            "aliases": ["turma", "class", "group", "class_group"],
        },
        {
            "key": "tipo_aula",
            "label": "Tipo de aula",
            "description": "Tipo de aula, por exemplo TP, PL ou T.",
            "required": False,
            "data_type": "string",
            "aliases": ["tipo aula", "tipo_aula", "tipo", "lesson_type", "class_type"],
        },
        {
            "key": "sala",
            "label": "Sala",
            "description": "Sala onde a aula decorre.",
            "required": True,
            "data_type": "string",
            "aliases": ["sala", "room"],
        },
        {
            "key": "caracteristicas_pedidas_para_sala",
            "label": "Características pedidas para sala",
            "description": "Características ou requisitos pedidos para a sala.",
            "required": False,
            "data_type": "string",
            "aliases": [
                "caracteristicas pedidas para sala",
                "características pedidas para sala",
                "requisitos sala",
                "room requirements",
                "requested room features",
            ],
        },
        {
            "key": "dia",
            "label": "Dia",
            "description": "Dia da aula.",
            "required": False,
            "data_type": "string",
            "aliases": ["dia", "day", "weekday"],
        },
        {
            "key": "dia_da_semana",
            "label": "Dia da semana",
            "description": "Por exemplo, segunda-feira, terça-feira, etc.",
            "required": False,
            "data_type": "string",
            "aliases": ["dia da semana", "dia_da_semana", "weekday", "week day"],
        },
        {
            "key": "semana",
            "label": "Semana",
            "description": "Número ou identificador da semana, quando aplicável.",
            "required": False,
            "data_type": "string",
            "aliases": ["semana", "week", "week_number"],
        },
        {
            "key": "hora_inicio",
            "label": "Hora de início",
            "description": "Hora de início da aula.",
            "required": True,
            "data_type": "time",
            "aliases": ["hora inicio", "hora_inicio", "inicio", "start time", "start_time", "begin", "start"],
        },
        {
            "key": "hora_fim",
            "label": "Hora de fim",
            "description": "Hora de fim da aula.",
            "required": True,
            "data_type": "time",
            "aliases": ["hora fim", "hora_fim", "fim", "end time", "end_time", "end"],
        },
        {
            "key": "numero_estudantes",
            "label": "Número de estudantes",
            "description": "Número de alunos inscritos ou esperados.",
            "required": False,
            "data_type": "number",
            "aliases": ["numero estudantes", "número estudantes", "alunos", "inscritos", "students", "num_students"],
        },
    ],
}